<!-- The entire header will link to the Home page -->
<a href="index.php">
	<!-- The id of the header is "" (none) so that the back to top button will link to the header and the webpage link will not change too much (only a # will appear at the webpage link) -->
	<header class="top" id="hdr">
		<img src="images/logoimg.jpg" alt="Logo" id="logoimg" height="70" width="80">		
		<!--Source: https://media.istockphoto.com/photos/laptop-with-blank-screen-isolated-on-black-background-picture-id1183047088?k=6&m=1183047088&s=612x612&w=0&h=1U0FFG0iIZSWjyF8nTBD0y62Dtk824CjixsLebouF3g=
			Reference: https://www.istockphoto.com/photos/laptop-black-background -->
		<h1>EZWeb - Laptop computer purchase website</h1>
	</header>
</a>