<footer>
	<hr />
	<!-- Author (my) information -->
	<p>Create by: Thanh An Nguyen. ID: 103125896.</p>
	<!-- Author email -->
	<p>Email: <a href="mailto:103125896@student.swin.edu.au" class="email">103125896@student.swin.edu.au</a></p>
	<!-- Disclaimer. Reference: -->
	<p>All names, characters, and events portrayed in this webpage are fictional.<br /> 
	Any similarity with other creative or real events or characters are purely coincidental.</p>
	<!-- The back to top button -->
	<a href="#hdr" id="backtotop">Back to top</a>
</footer>